GET http://localhost:3000


###
GET http://localhost:3000/protected
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MDI0NDgyNDUsImV4cCI6MTcwMjQ0ODg0NX0.l7WhhNZ6QWsBtSFoPMZ0e3Z6fFYaKMCA7up4P68z6xsd6B7WqM2IshACDk-rkGC7Yvysog71O8hUo3RloW_UKFXWuiyEarC-Bapi0OXgp0dMLYtNZaYQDEvi2OnmuKem0Mt2mQoPC9yOPegea8w_CE_dyYagLzN2rgtLPqD0cefxx5jXWNpbttfbukwa5E5x2gayztDM_K8IByDk2dgR5fML_XQsaMj2CYASQijmOlWMDbeKq5-tdKS4C6ssb8BB-GTP3ZrU_bAFeuqlhZikmFV1PDE9b3I_5xobeHmkc8rJjkwioVxf_BnOdmsAy-dm2fokAHcXY8XaADapZvzktYns7njbTNOdhRTOx2YYvQZeSg3r-y0Qy9ksMnyXNph8IIT65lJ1YROEMGEBbq4BIMY1OwljwE4iuej2Uxq4TYRR7J7-maWgbCmWXae2ETUt1ZLNCP0L89XS8UxcJORf_slyqQ1mN1h32a8-nl91-aoKM_-AzVkxUDyiGapl648y